# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abenaiss <abenaiss@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/22 21:34:43 by abenaiss          #+#    #+#              #
#    Updated: 2021/07/22 21:40:53 by abenaiss         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Bureaucrat

OBJ_DIR = ./obj

CFLAG = -Wall -Wextra -Werror

IFILES = Bureaucrat.hpp
CFILES = main.c\
		Bureaucrat.cpp\

$(NAME): 
	@echo "Compiling $(NAME)..."
clean:
	@echo "Cleaning $(NAME)..."
	rm -rf $(NAME)
	@echo "Done."
fclean: